# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2
#version: 2

# Personal info
name: 윤원희
title: 도전과제에 두려움 없이 즐기는 개발자입니다.
email: wony9324@naver.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  younwony

# <mark>아무것도 하지 않으면 아무 일도 일어나지 않는다</mark> <br>
# About Section
about_title: 소개
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java와 Spring을 사용하는 백엔드 개발자로서, <mark>고객 중심</mark>의 사고, <mark>소프트웨어 품질</mark>의 지속적인 개선, 원활한 <mark>커뮤니케이션</mark>, 그리고 효율적인 <mark>시스템 자동화</mark>를 통해 비즈니스 가치를 창출하는 데 집중해 왔습니다.<br>
  <br>
  <mark>고객 중심</mark> 분석을 통해 비즈니스의 성장에 기여할 수 있었습니다. BigQuery 및 Google Analytics를 사용하여 고객 행동 패턴을 분석하고, 주요 고객층을 대상으로 리서치를 진행했습니다. 이 데이터를 기반으로 문제를 파악하고 해결책을 제시하며, 실질적인 비즈니스 방향을 도출할 수 있었습니다.<br>
  <br>
  <mark>소프트웨어 품질</mark> 개선에 대한 깊은 관심을 가지고 있습니다. 코드 리뷰를 도입하여 팀의 컨벤션을 정립하고, 코드 공유와 협업을 통해 팀의 성장을 이끌었습니다.<br>
  <br>
  <mark>커뮤니케이션</mark>은 제가 가장 중요하게 생각하는 핵심 가치입니다. 팀원들과의 활발한 소통을 통해 문제를 단순화하고, 최적의 해결책을 도출하여 효율적인 협업을 실현할 수 있었습니다.<br>
  <br>
  <mark>시스템 자동화</mark>를 통해 반복적인 작업을 제거하고, 효율성을 극대화하여 팀의 생산성을 증가시켰습니다.<br>
more_content: | # this will include new lines to allow paragraphs
   - [개인 블로그](https://youn12.tistory.com/)

# Footer
footer_show_references: false
references_title:
#references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
